#pragma once
#include <inttypes.h>
#include <rte_cycles.h>
#include <rte_eal.h>
#include <rte_ethdev.h>
#include <rte_launch.h>
#include <rte_lcore.h>
#include <rte_mbuf.h>
#include <stdint.h>
#include "nf.h"
#include "nat_main.h"
#include "fake_dpdk/fake_io.h"
#include "utils/vigor-time.h"